name: Publish Pages
'on':
  push:
    branches:
    - main
  workflow_dispatch: null
  schedule:
  - cron: 17 * * * *
permissions:
  contents: read
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    with:
      pages_artifact: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - id: deployment
      uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
